// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB7kEaqr4N-lTqUfFN-MgryqI9GbRiwjc',
    appId: '1:190830206605:web:bf022e52e4c2c41563ccc4',
    messagingSenderId: '190830206605',
    projectId: 'fir-17529',
    authDomain: 'fir-17529.firebaseapp.com',
    storageBucket: 'fir-17529.firebasestorage.app',
    measurementId: 'G-7Z120J6D34',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW6YZrI1ygbym9ypZ83Uw9Ypt6a5dIKHA',
    appId: '1:190830206605:android:822fddad3c5131b863ccc4',
    messagingSenderId: '190830206605',
    projectId: 'fir-17529',
    storageBucket: 'fir-17529.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4MNQI2Vx-XusPN0kZQjfqOTIHc4ubwCI',
    appId: '1:190830206605:ios:6e46b8b62238e27163ccc4',
    messagingSenderId: '190830206605',
    projectId: 'fir-17529',
    storageBucket: 'fir-17529.firebasestorage.app',
    iosBundleId: 'com.thebharatworks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4MNQI2Vx-XusPN0kZQjfqOTIHc4ubwCI',
    appId: '1:190830206605:ios:6e46b8b62238e27163ccc4',
    messagingSenderId: '190830206605',
    projectId: 'fir-17529',
    storageBucket: 'fir-17529.firebasestorage.app',
    iosBundleId: 'com.thebharatworks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAB7kEaqr4N-lTqUfFN-MgryqI9GbRiwjc',
    appId: '1:190830206605:web:08fb1dc96851664c63ccc4',
    messagingSenderId: '190830206605',
    projectId: 'fir-17529',
    authDomain: 'fir-17529.firebaseapp.com',
    storageBucket: 'fir-17529.firebasestorage.app',
    measurementId: 'G-CRN5BDB3HD',
  );
}
